# Generated by Django 2.2.20 on 2024-12-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_confirmed_no_alphabet_affiliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirmed_no_alphabet_affiliation',
            field=models.BooleanField(default=False, help_text='User must confirm that they are not associated with any Alphabet portfolio company'),
        ),
    ]
