# Generated by Django 2.2.20 on 2025-01-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20241202_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirmed_no_alphabet_affiliation',
            field=models.BooleanField(default=False),
        ),
    ]
