# Generated by Django 2.2.20 on 2025-01-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_auto_20230804_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('submitted', 'submitted'), ('running', 'running'), ('failed', 'failed'), ('cancelled', 'cancelled'), ('resuming', 'resuming'), ('queued', 'queued'), ('finished', 'finished'), ('submitting', 'submitting'), ('archived', 'archived'), ('partially_evaluated', 'partially_evaluated'), ('evaluating', 'evaluating')], db_index=True, max_length=30),
        ),
    ]